/// Flutter icons SideIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SideIcons
///      fonts:
///       - asset: fonts/SideIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SideIcons {
  SideIcons._();

  static const _kFontFam = 'SideIcons';
  static const String? _kFontPkg = null;

  static const IconData attacker_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData defender_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
